#pragma once

class CBaseEntity;
class CBasePlayer;

void RegisterFutureGameplayCvars();
void UpdateFutureGameplayHooksFrame();
bool FutureGameplayPlayerCanRespawn(CBasePlayer *pPlayer);
bool FutureGameplayPlayerCanTakeDamage(CBasePlayer *pPlayer, CBaseEntity *pAttacker);
int FutureGameplayPlayerRelationship(CBaseEntity *pPlayer, CBaseEntity *pTarget);
void FutureGameplayOnPlayerInitHUD(CBasePlayer *pPlayer);
void FutureGameplayApplyPlayerSpawnOverride(CBasePlayer *pPlayer);
void FutureGameplayOnPlayerSpawn(CBasePlayer *pPlayer);
void FutureGameplayOnPlayerKilled(CBasePlayer *pVictim, CBasePlayer *pKiller);
void FutureGameplayOnClientDisconnected(CBasePlayer *pPlayer);
bool ExpPistolTapFireEnabled();
float ExpMoveSpreadScale();
bool ExpFirstShotAccuracyEnabled();
float ExpSpreadRecoverySeconds();
const char *ExpWeaponUnderTest();
const char *ExpGlockProfileName();
const char *ExpSessionTag();
const char *ExpMatrixName();
const char *ExpMatrixStep();
float ExpGlockPrimaryBaseSpread();
float ExpGlockPrimaryGroundMovePenalty();
float ExpGlockPrimaryAirMovePenalty();
float ExpGlockPrimaryDuckPenaltyScale();
float ExpGlockPrimaryShotGrowth();
float ExpGlockPrimaryFirstShotSpeedThreshold();
float ExpGlockPrimaryMaxSpread();
bool ExpGlockPatternModeEnabled();
float ExpGlockPatternScaleX();
float ExpGlockPatternScaleY();
float ExpGlockPatternResetTime();
int ExpGlockPatternMaxIndex();
float ExpGlockPrimaryDamage();
float ExpGlockPrimaryHeadshotScale();
bool ExpGlockPrimaryHeadshotLethal();
bool ExpDebugWeaponLogEnabled();
bool ExpDebugWeaponLogRejectionsEnabled();
bool ExpGlockExperimentalModeEnabled();
bool ExpMP5ExperimentalModeEnabled();
bool Exp357ExperimentalModeEnabled();
bool ExpShotgunExperimentalModeEnabled();
const char *ExpMP5ProfileName();
const char *Exp357ProfileName();
const char *ExpShotgunProfileName();
bool ExpMP5PrimaryEnabled();
bool Exp357PrimaryEnabled();
bool ExpShotgunPrimaryEnabled();
float ExpMP5PrimaryBaseSpread();
float Exp357PrimaryBaseSpread();
float ExpShotgunPrimaryBaseSpread();
float ExpMP5PrimaryGroundMovePenalty();
float Exp357PrimaryGroundMovePenalty();
float ExpShotgunPrimaryGroundMovePenalty();
float ExpMP5PrimaryAirMovePenalty();
float Exp357PrimaryAirMovePenalty();
float ExpShotgunPrimaryAirMovePenalty();
float ExpMP5PrimaryDuckPenaltyScale();
float Exp357PrimaryDuckPenaltyScale();
float ExpShotgunPrimaryDuckPenaltyScale();
float ExpMP5PrimaryBurstGrowth();
float ExpMP5PrimaryBurstMaxAdditionalSpread();
float ExpMP5PrimarySpreadRecoverySeconds();
bool ExpMP5PatternModeEnabled();
float ExpMP5PatternScaleX();
float ExpMP5PatternScaleY();
float ExpMP5PatternResetTime();
int ExpMP5PatternMaxIndex();
float Exp357PrimarySpreadRecoverySeconds();
float ExpShotgunPrimarySpreadRecoverySeconds();
float ExpMP5PrimaryDamage();
float Exp357PrimaryDamage();
float ExpShotgunPrimaryDamagePerPellet();
int ExpShotgunPrimaryPelletCount();
float ExpMP5PrimaryHeadshotScale();
float Exp357PrimaryHeadshotScale();
float ExpShotgunPrimaryHeadshotScale();
bool ExpMP5PrimaryHeadshotLethal();
bool Exp357PrimaryHeadshotLethal();
bool ExpShotgunPrimaryHeadshotLethal();
bool ExpMP5PrimaryFirstShotAccuracyEnabled();
bool Exp357PrimaryFirstShotAccuracyEnabled();
bool ExpShotgunPrimaryFirstShotAccuracyEnabled();
float ExpMP5PrimaryFirstShotSpeedThreshold();
float Exp357PrimaryFirstShotSpeedThreshold();
float ExpShotgunPrimaryFirstShotSpeedThreshold();
float ExpMP5PrimaryMaxSpread();
float Exp357PrimaryMaxSpread();
float ExpShotgunPrimaryMaxSpread();
bool ExpMP5LabLoadoutEnabled();
float ExpMP5LabAmmo();
bool ExpMP5LabAutoswitch();
bool Exp357LabLoadoutEnabled();
float Exp357LabAmmo();
bool Exp357LabAutoswitch();
bool ExpShotgunLabLoadoutEnabled();
float ExpShotgunLabAmmo();
bool ExpShotgunLabAutoswitch();
bool ExpRoundModeEnabled();
float ExpRoundFreezeTimeSeconds();
float ExpRoundRestartDelaySeconds();
float ExpRoundStartHealth();
float ExpRoundStartArmor();
bool ExpRoundNoRespawn();
bool ExpRoundFriendlyFireEnabled();
const char *ExpRoundWeaponProfile();
const char *ExpRoundLoadoutMode();
bool ExpTeamRoundModeEnabled();
bool ExpTeamRoundTeamplayEnabled();
const char *ExpTeamRoundSpawnMode();
const char *ExpTeamRoundTeam1Name();
const char *ExpTeamRoundTeam2Name();
const char *ExpTeamRoundTeam1Loadout();
const char *ExpTeamRoundTeam2Loadout();
float ExpTeamRoundTeam1Health();
float ExpTeamRoundTeam2Health();
float ExpTeamRoundTeam1Armor();
float ExpTeamRoundTeam2Armor();
bool ExpMatchModeEnabled();
float ExpMatchRoundsToWin();
float ExpMatchMaxRounds();
bool ExpMatchEnableHalftime();
float ExpMatchHalftimeAfterRound();
bool ExpMatchSideSwapEnabled();
bool ExpMatchResetMoneyOnHalftime();
bool ExpMatchResetLoadoutOnHalftime();
bool ExpMatchAutoRestartAfterEnd();
float ExpMatchEndDelaySeconds();
bool ExpMatchActive();
bool ExpMatchEnded();
int ExpMatchNumber();
int ExpMatchCurrentRoundNumber();
int ExpMatchScoreForLogicalTeam(int logicalTeamId);
const char *ExpMatchLogicalTeamName(int logicalTeamId);
int ExpMatchLogicalTeamForPhysicalTeam(int physicalTeamId);
bool ExpMatchHalftimeOccurred();
bool ExpMatchSideSwapActive();
const char *ExpMatchWinnerName();
const char *ExpMatchEndReason();
bool ExpBuyModeEnabled();
bool ExpBuyFreezeOnlyEnabled();
bool ExpBuyTeamSharedCatalogEnabled();
float ExpBuyStartMoney();
float ExpBuyRoundWinReward();
float ExpBuyRoundLossReward();
float ExpBuyMaxMoney();
bool ExpBuyAllowGlock();
bool ExpBuyAllowMp5();
bool ExpBuyAllow357();
bool ExpBuyAllowShotgun();
bool ExpBuyAllowArmor();
bool ExpBuyAllowHelmet();
bool ExpBuyAllowHandGrenade();
float ExpBuyCostGlock();
float ExpBuyCostMp5();
float ExpBuyCost357();
float ExpBuyCostShotgun();
float ExpBuyCostArmor();
float ExpBuyCostHelmet();
float ExpBuyCostHandGrenade();
bool ExpArmorModeEnabled();
float ExpArmorStartValue();
float ExpArmorMaxValue();
float ExpArmorHealthFraction();
float ExpArmorDrainScale();
bool ExpHelmetModeEnabled();
bool ExpHelmetStartEnabled();
bool ExpHelmetHeadshotProtectionEnabled();
bool FutureGameplayPlayerHasHelmet(CBasePlayer *pPlayer);
bool FutureGameplayPlayerHeadProtectionActive(CBasePlayer *pPlayer);
void FutureGameplayMarkPlayerBulletArmorHandled(CBasePlayer *pPlayer);
bool FutureGameplayConsumePlayerBulletArmorHandled(CBasePlayer *pPlayer, int bitsDamageType);
int ExpRoundConnectedPlayersForTeam(int teamId);
int ExpRoundAlivePlayersForTeam(int teamId);
int ExpRoundUnassignedConnectedPlayers();
int ExpRoundUnassignedAlivePlayers();
const char *ExpRoundLastWinnerTeamName();
bool ExpRoundModeActive();
bool ExpRoundLive();
bool ExpCfgDrivenModeActive();
const char *ExpActiveCfgProfile();
const char *ExpLastSuccessfulCfgProfile();
const char *ExpLastCfgAction();
const char *ExpLastCfgAppliedAt();
bool ExpGlockLabDummyEnabled();
const char *ExpGlockLabDummyDisplayName();
const char *ExpGlockLabTargetProfileName();
float ExpGlockLabDummyHealth();
float ExpGlockLabDummyArmor();
bool ExpGlockLabDummyHeadProtected();
float ExpGlockLabDummyArmorHealthFraction();
float ExpGlockLabDummyArmorDrainScale();
bool ExpGlockLabDummyAutoRespawnEnabled();
float ExpGlockLabDummyRespawnDelaySeconds();
float ExpGlockLabDummySpawnDistance();
const char *ExpGlockLabDummyModel();
bool ExpGlockLabDummyFacePlayer();
float ExpGlockLabDummyOffsetRight();
float ExpGlockLabDummyOffsetUp();
bool IsExpGlockLabDummyEntity(CBaseEntity *pEntity);
