#pragma once

class CBaseEntity;

void RegisterFutureGameplayCvars();
void UpdateFutureGameplayHooksFrame();
bool ExpPistolTapFireEnabled();
float ExpMoveSpreadScale();
bool ExpFirstShotAccuracyEnabled();
float ExpSpreadRecoverySeconds();
const char *ExpWeaponUnderTest();
const char *ExpGlockProfileName();
const char *ExpSessionTag();
const char *ExpMatrixName();
const char *ExpMatrixStep();
float ExpGlockPrimaryBaseSpread();
float ExpGlockPrimaryGroundMovePenalty();
float ExpGlockPrimaryAirMovePenalty();
float ExpGlockPrimaryDuckPenaltyScale();
float ExpGlockPrimaryFirstShotSpeedThreshold();
float ExpGlockPrimaryMaxSpread();
float ExpGlockPrimaryDamage();
float ExpGlockPrimaryHeadshotScale();
bool ExpGlockPrimaryHeadshotLethal();
bool ExpDebugWeaponLogEnabled();
bool ExpDebugWeaponLogRejectionsEnabled();
bool ExpGlockExperimentalModeEnabled();
bool ExpMP5ExperimentalModeEnabled();
const char *ExpMP5ProfileName();
bool ExpMP5PrimaryEnabled();
float ExpMP5PrimaryBaseSpread();
float ExpMP5PrimaryGroundMovePenalty();
float ExpMP5PrimaryAirMovePenalty();
float ExpMP5PrimaryDuckPenaltyScale();
float ExpMP5PrimaryBurstGrowth();
float ExpMP5PrimaryBurstMaxAdditionalSpread();
float ExpMP5PrimarySpreadRecoverySeconds();
float ExpMP5PrimaryDamage();
float ExpMP5PrimaryHeadshotScale();
bool ExpMP5PrimaryHeadshotLethal();
bool ExpMP5PrimaryFirstShotAccuracyEnabled();
float ExpMP5PrimaryFirstShotSpeedThreshold();
float ExpMP5PrimaryMaxSpread();
bool ExpMP5LabLoadoutEnabled();
float ExpMP5LabAmmo();
bool ExpMP5LabAutoswitch();
bool ExpCfgDrivenModeActive();
const char *ExpActiveCfgProfile();
const char *ExpLastSuccessfulCfgProfile();
const char *ExpLastCfgAction();
const char *ExpLastCfgAppliedAt();
bool ExpGlockLabDummyEnabled();
const char *ExpGlockLabDummyDisplayName();
const char *ExpGlockLabTargetProfileName();
float ExpGlockLabDummyHealth();
float ExpGlockLabDummyArmor();
bool ExpGlockLabDummyHeadProtected();
float ExpGlockLabDummyArmorHealthFraction();
float ExpGlockLabDummyArmorDrainScale();
bool ExpGlockLabDummyAutoRespawnEnabled();
float ExpGlockLabDummyRespawnDelaySeconds();
float ExpGlockLabDummySpawnDistance();
const char *ExpGlockLabDummyModel();
bool ExpGlockLabDummyFacePlayer();
float ExpGlockLabDummyOffsetRight();
float ExpGlockLabDummyOffsetUp();
bool IsExpGlockLabDummyEntity(CBaseEntity *pEntity);
